### ISSUE TITLE
Provide more information for CP3108B

### ISSUE THREAD

**Issue by nicholasluimy** [nushackers/notes-to-cs-freshmen-from-the-future#4]
Under interesting courses in SoC

- Linking to NUS Orbital as a programme that awards credits under CP3108B
- [website](https://orbital.comp.nus.edu.sg/)
- [facebook](https://www.facebook.com/nus.orbital)

**Comment by ejamesc** [comment]
Your pull request is welcomed.

**Comment by ejamesc** [comment]
👍 👍  Thank you!

**Comment by nicholasluimy** [comment]
Great job with starting this list guys, i'd love to help out when i'm back at nus :)
