### ISSUE TITLE
I've been curating my own list of knowledge and links, perhaps you can add it here too

### ISSUE THREAD

**Issue by nikitavoloboev** [nushackers/notes-to-cs-freshmen-from-the-future#5]
I do it as a [mind map of everything](https://github.com/nikitavoloboev/knowledge-map) but its not just computer science. It's math, physics and everything in-between. 

Really like this list you have made. :)

**Comment by jin** [comment]
Nice work! I feel that it's too general to be included in the list, but thanks for suggesting :-)
